### ISSUE TITLE
drawImage shows white noise

### ISSUE THREAD

**Issue by lorhof1** [rdagger/micropython-ssd1351#3]
Hello, so I have an image (bg.raw) which i converted to raw using some png to raw converter. Now, i've used `display.draw_image("bg.raw", 0, 0, 128, 128)` (it's in the root dir) but the display shows white noise only. What am I doing wrong?

**Comment by lorhof1** [comment]
[bg.zip](https://github.com/rdagger/micropython-ssd1351/files/7078936/bg.zip)

**Comment by rdagger** [comment]
The image you uploaded is a PNG file.  I wrote a utility called img2rgb565.py to convert standard image formats such as PNG and JPEG to the required RGB565 RAW format.  It is in the repo's util folder.

**Comment by lorhof1** [comment]
Thank you, that worked.
