### ISSUE TITLE
Transparent text background?

### ISSUE THREAD

**Issue by lorhof1** [rdagger/micropython-ssd1351#4]
Hello, is it possible to keep the pixels that are where the text background is?

**Comment by rdagger** [comment]
I added a transparent parameter to the draw_text method to provide transparent backgrounds.  Unfortunately, it is a bit slow compared to the regular drawing method.  You can always specify the background color when drawing fonts which is faster.

I also added a method draw_text8x8 which uses the built-in MicroPython 8x8 font.  It doesn't support transparent backgrounds, but it uses frame buffers which you could modify to insert your own graphics behind the text.

I also cleaned up landscaping drawing to be clockwise on the origin.

**Comment by rdagger** [comment]
There are 2 new demos for the new features.

**Comment by lorhof1** [comment]
thanks
