### ISSUE TITLE
a way to color a sprite?

### ISSUE THREAD

**Issue by MimiVRC** [rdagger/micropython-ssd1351#9]
the sh1106 library lets you make "sprites" by loading data into a framebuffer using a color mode of your choice, such as this

```
import framebuf

RED = (255, 0, 0)

def LoadSprite(filename, width, height):
        # print(file)
        with open(filename, 'rb') as f:
            f.readline() # magic number
            f.readline() # creator comment
            f.readline() # dimensions
            data = bytearray(f.read())
        return framebuf.FrameBuffer(data, width, height, framebuf.MONO_HLSB)
        
GirlR = LoadSprite('GirlR.PBM', width=16, height=16)

```
and then you can display it onto the screen like this 
`
display.blit(GirlR, 64, 35, 0, RED)`

buffer, x, y, key(invisible color), color of sprite(optional)

where this is what blit is doing, which seems very similar to the "draw_sprite" except you can't select a key (invisible color) or a color to use for the sprite.

```
def blit(self, fbuf, x, y, key=-1, palette=None):
        super().blit(fbuf, x, y, key, palette)
        self.register_updates(y, y+self.height)
```

pretty much just curious how hard it would be to expand on draw_sprite to support any framebuffer color mode and drawing with the key and color selection. 

I'm very new to all of this and found my sh1106 screen to be very easy to work with like this (and uses very little ram) but I really wanted to move onto a color oled!

**Comment by rdagger** [comment]
You can use framebuf with sprites to achieve similar results. 

For example, in the image below I draw an ostrich sprite with a green background ![Ostrich65x64](https://github.com/rdagger/micropython-ssd1351/assets/106355/e8d43f25-2b6f-4eb9-8654-0971495dc6ce) over a landscape sprite.
![ostrich](https://github.com/rdagger/micropython-ssd1351/assets/106355/396ca321-8e2f-4505-9b15-53a42618c3e4)


I added a demo to the project called demo_framebuffer.py for the above example.

I don't want to modify the base code because this approach is memory intensive and would preclude use on less powerful boards.

**Comment by MimiVRC** [comment]
oh thank you for the demo! read over it and it seems very simple! I will test it later but do you know if this would also let me use my own color modes? I have been working on a game and only need 16 colors or so (because of they style) so I wouldn't really use RGB565. 

thank you for the quick response and very clear sample!

**Comment by rdagger** [comment]
This SSD1351 library supports 16-bit color, but the display can handle 18-bit color as well. In earlier datasheets, there was mention of an 8-bit mode by setting REMAP 0x74 [7:6] to 0, but this detail is omitted in later datasheets. So, it's uncertain if the display natively supports a 256-color mode. You could try it out to see. 

Alternatively, you can overlay a framebuffer with lower color depth onto one with higher color depth. To do this, you need to create a palette that defines the corresponding high-depth colors for each of the lower-depth framebuffer colors.

**Comment by MimiVRC** [comment]
experimented a lot tonight and if you want any solid single colored sprites, you can use tiny .PBM files for sprites 

```
    def LoadSprite(filename, width, height):
        with open(filename, 'rb') as f:
            f.readline() # magic number
            f.readline() # creator comment
            f.readline() # dimensions
            data = bytearray(f.read())
        return framebuf.FrameBuffer(data, width, height, framebuf.MONO_HLSB)

    GirlR = LoadSprite('GirlR.PBM', width=16, height=16)
```

make some predefined colors (I had to swap around the colors because it was displaying as BRG

```
    def make_color(R, G, B):

        bg = 0x0000
        COLOR = color565(B, R, G)
        
        #the above is BRG since that is how my display displays colors. swap the order of these to whatever your display is 

        palette = FrameBuffer(bytearray(2 * 1 * 2), 2, 1, RGB565)
        palette.pixel(0, 0, bg)
        palette.pixel(1, 0, COLOR)
        
        return palette
    
    PINK = make_color(31, 0, 31)
    RED = make_color(31, 0, 0)
    GREEN = make_color(0, 63, 0)
    BLUE = make_color(0, 0, 31)
    SKY_BLUE = make_color(0, 54, 31)
    DARK_GREEN = make_color(0, 39, 3)
    BLOOD_RED = make_color(19, 5, 2)
```

and then blit it as any color you want as shown in your example 

```
backgroundFB.blit(GirlR, 64, 64, 0, RED)
display.draw_sprite(background, 0, 0, 128, 128)

```

wanted to document this for anyone coming along later wondering the same thing. it was a pain to figure out how to make a palette for this, Darius on the Micropython discord helped me find the correct syntax!

**Comment by rdagger** [comment]
I added an example called demo_pbm.py based on your code.  Thanks for the contribution!

![Invaders](https://github.com/rdagger/micropython-ssd1351/assets/106355/673779bd-288d-4ecb-bb92-ad76dfef05c4)

**Comment by MimiVRC** [comment]
oh that demo looks great! thank you!
